// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:3efae184-aec2-4169-8cba-5b90e4a1025a',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_RGwFGlUop',
  aws_user_pools_web_client_id: '7ut23ndmv5pnjuqsv2daiubsi',
  oauth: {},
};

export default awsmobile;
